const stages=[['raw','Raw material','Steel coils','🧱'],['slitting','Slitting line','Cut coils into strips','✂️'],['coilpack','Coil packing','Pack strip coils','📦'],['wip','Inter-operation stock','WIP / transport','🏗️'],['forming','Forming & welding','Shape and weld pipe','⚙️'],['cooling','Cooling','Post-weld cooling','💧'],['calibration','Calibration','Diameter & weld check','📏'],['cutting','Pipe cutting','Cut to order length','🪚'],['qc','Quality control','Inspection','🔎'],['packaging','Packaging','Bundle & label','📦'],['fg','Finished goods','Storage & dispatch','🚚']];
const current={
raw:{title:'Raw material',subtitle:'Steel coils are received and stored before entering the slitting line.',kpis:[['Role','Input inventory'],['Material','Steel coils'],['Flow issue','Storage / waiting'],['Data focus','Inventory, dwell time']],activities:['Receive steel coils','Store and prepare coils for production'],issues:['Inventory can contribute significantly to total lead time.','Material availability influences downstream continuity.']},
slitting:{title:'Slitting line',subtitle:'Steel rolls are cut longitudinally into strips before pipe production.',kpis:[['Operators','2'],['Cycle time','50 min'],['Operation time','20 min'],['Changeover','~2 h / shift'],['VA + necessary NVA','30.5 min'],['OEE','65.91%']],activities:['Load steel coil','Set knives and shafts','Cut roll into strips','Prepare strips for downstream production'],issues:['Long changeovers reduce availability.','VSM identified this as a major improvement opportunity.']},
coilpack:{title:'Coil packing',subtitle:'Steel strips are packed after slitting using polypropylene tape.',kpis:[['Time / strip','28 s'],['Strips / roll','10'],['Time / roll','280 s'],['Tape waste','80 kg / month'],['Packaging cost','€12.50 / roll'],['Improvement focus','Material reuse']],activities:['Collect slit strips','Wrap strips with tape','Prepare coils for transport/storage'],issues:['Packaging creates material cost and waste.','The paper proposes reuse of polypropylene tape.']},
wip:{title:'Inter-operation stock',subtitle:'Material waits and is transported between production stages.',kpis:[['Role','WIP inventory'],['Flow issue','Waiting / transport'],['Data focus','WIP quantity'],['Lead-time effect','Potentially high']],activities:['Store intermediate material','Move material between production areas'],issues:['WIP can hide flow problems.','Waiting and transport are non-value-added activities.']},
forming:{title:'Forming & welding',subtitle:'Steel strip is formed into a pipe blank and welded continuously.',kpis:[['Process','Continuous forming'],['Joining','High-frequency welding'],['Input','Prepared strip coils'],['Data focus','Speed, weld parameters']],activities:['Unwind strip','Join strip ends','Form round tube blank','High-frequency weld'],issues:['Performance depends on strip quality and setup.','Process data can support stability and traceability.']},
cooling:{title:'Cooling',subtitle:'The welded pipe is cooled in an emulsion bath immediately after welding.',kpis:[['Role','Post-weld cooling'],['Flow nature','Continuous'],['Data focus','Temperature / flow'],['Purpose','Stabilise product']],activities:['Cool welded pipe','Stabilise before calibration'],issues:['Process continuity and thermal conditions influence downstream quality.']},
calibration:{title:'Calibration',subtitle:'Final pipe diameter is shaped and the weld is checked ultrasonically.',kpis:[['Purpose','Dimensional accuracy'],['Quality method','Ultrasonic test'],['Output','Pipe ready for cutting'],['Data focus','Diameter, weld quality']],activities:['Calibrate final diameter','Perform ultrasonic inspection','Verify weld quality'],issues:['Inspection may reveal upstream problems.','Quality data can support earlier defect prevention.']},
cutting:{title:'Pipe cutting',subtitle:'The continuous pipe is cut automatically to the specified order length.',kpis:[['Operation','Automatic cutting'],['Control basis','Measured length'],['Output','Ordered pipe lengths'],['Data focus','Length accuracy']],activities:['Measure pipe length','Cut to required dimension'],issues:['Synchronization and accuracy are essential to avoid rejection or rework.']},
qc:{title:'Quality control',subtitle:'Visual inspection and quality checks support conformity verification.',kpis:[['Baseline defectives','1 piece'],['After improvement','0 pieces'],['Annual shortage rate','2%'],['Focus','Quality system outcome']],activities:['Inspect surface','Verify conformity','Check first tube when required'],issues:['Inspection detects problems; prevention requires upstream process capability.']},
packaging:{title:'Packaging',subtitle:'Pipes are packed, labelled, drained and moved to finished goods.',kpis:[['Main operations','Manual bundling'],['Handling','Drain emulsion'],['Transport','Overhead crane'],['Data focus','Time, handling, errors']],activities:['Bundle pipes','Attach label','Drain emulsion','Transfer finished bundles'],issues:['Manual handling remains important.','Necessary logistics do not directly transform the product.']},
fg:{title:'Finished goods',subtitle:'Finished pipe bundles are stored before dispatch.',kpis:[['Role','Finished goods inventory'],['Flow issue','Storage / dispatch'],['Position','End of value stream'],['Data focus','Inventory, dwell time']],activities:['Store bundles','Prepare dispatch'],issues:['Finished-goods inventory can extend fulfilment time and reduce responsiveness.']}
};
const improved={slitting:{title:'Slitting line – improvement view',subtitle:'The VSM analysis identified the slitting line as the strongest improvement opportunity.',kpis:[['Operators','2'],['Changeover','1 h'],['VA + necessary NVA','40 min (80%)'],['Produced details','35 pieces'],['Availability','86.36%'],['OEE','79.55%']],activities:['Use a replaceable knife/shaft section','Perform retooling during machine waiting time','Release one extra productive hour per shift'],issues:['Reported productivity increase: about 17%.','Implementation requires investment and production planning.']},coilpack:{title:'Coil packing – improvement view',subtitle:'The paper proposes reducing packing waste through tape reuse.',kpis:[['Packaging cost / roll','€6.55'],['Monthly cost','€786'],['Annual cost','€9,432'],['Annual difference','€8,568'],['Waste focus','Lower tape demand'],['Improvement','Reuse tape']],activities:['Leave longer tape ends','Reuse polypropylene tape where feasible'],issues:['Potential risk: deterioration of belt strength with repeated reuse.']}};
let mode='current',selected='slitting';
const flow=document.getElementById('flow');
stages.forEach(([id,name,desc,icon])=>{const b=document.createElement('button');b.className='stage';b.dataset.id=id;b.innerHTML=`<b>${icon} ${name}</b><small>${desc}</small>`;b.addEventListener('click',()=>{selected=id;render()});flow.appendChild(b)});
const els={title:document.getElementById('stationTitle'),subtitle:document.getElementById('stationSubtitle'),icon:document.getElementById('stationIcon'),kpis:document.getElementById('kpis'),activities:document.getElementById('activities'),issues:document.getElementById('issues'),oee:document.getElementById('headlineOee'),oeeText:document.getElementById('headlineOeeText'),note:document.getElementById('modeNote')};
function list(items){return '<ul>'+items.map(x=>`<li>${x}</li>`).join('')+'</ul>'}
function render(){const d=(mode==='improved'&&improved[selected])?improved[selected]:current[selected];els.title.textContent=d.title;els.subtitle.textContent=d.subtitle;els.icon.textContent=stages.find(s=>s[0]===selected)[3];els.kpis.innerHTML=d.kpis.map(([a,b])=>`<div class="mini"><small>${a}</small><strong>${b}</strong></div>`).join('');els.activities.innerHTML=list(d.activities);els.issues.innerHTML=list(d.issues);document.querySelectorAll('.stage').forEach(x=>{x.classList.toggle('active',x.dataset.id===selected);x.classList.toggle('target',mode==='improved'&&['slitting','coilpack'].includes(x.dataset.id))});els.oee.textContent=mode==='improved'?'79.55%':'65.91%';els.oeeText.textContent=mode==='improved'?'After slitting-line improvement.':'Before improvement.'}
function setMode(m){mode=m;if(mode==='improved'&&!['slitting','coilpack'].includes(selected))selected='slitting';document.getElementById('currentBtn').classList.toggle('active',m==='current');document.getElementById('improvedBtn').classList.toggle('active',m==='improved');els.note.classList.toggle('show',m==='improved');render()}
document.getElementById('currentBtn').onclick=()=>setMode('current');document.getElementById('improvedBtn').onclick=()=>setMode('improved');render();